// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckWAF() {
  return window['go']['main']['App']['CheckWAF']();
}

export function Fingerprint(arg1) {
  return window['go']['main']['App']['Fingerprint'](arg1);
}

export function GetTarget(arg1) {
  return window['go']['main']['App']['GetTarget'](arg1);
}

export function Injection(arg1) {
  return window['go']['main']['App']['Injection'](arg1);
}

export function Interpreter() {
  return window['go']['main']['App']['Interpreter']();
}

export function Resolver() {
  return window['go']['main']['App']['Resolver']();
}

export function SetTarget(arg1, arg2) {
  return window['go']['main']['App']['SetTarget'](arg1, arg2);
}
