// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckWAF():Promise<{[key: string]: string}>;

export function Fingerprint(arg1:string):Promise<{[key: string]: string}>;

export function GetTarget(arg1:string):Promise<string>;

export function Injection(arg1:string):Promise<{[key: string]: string}>;

export function Interpreter():Promise<string>;

export function Resolver():Promise<{[key: string]: string}>;

export function SetTarget(arg1:string,arg2:string):Promise<void>;
