name: golangci-lint
on: [push, pull_request]
jobs:
  golangci:
    name: lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: actions/setup-go@v4
        with:
          go-version: "1.23.3"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=10m
